### PR TITLE
Merged master and updated jts-core to 1.18.x

### PR DESCRIPTION
**Pull request by tboegner**
This PR brings following changes:

- Master was merged since it contains bugfixes.
- Main goal is to update jts-core to 1.18.x in order to be compatible with recent versions of Spring Boot (2.3.x+).
- Update to Java 8 done, should be unproblematic (all tests are green).
- Some maven plugins were also pulled up to their newest versions.

### CODE REVIEW

**Comment by karussell** [comment]
Thanks for your contribution.

The `gh` branch is for the usage in our routing engine alone and we need to keep it align with the used jackson and jts versions there: https://github.com/graphhopper/graphhopper/pull/1803#issuecomment-657569269. So we would first need to update the versions there.

**Comment by tboegner** [comment]
I see. Maybe another branch rooted from `gh` would be better for this PR. I could also change the PR for master, if you like.
Would you then deploy this to maven central (e.g. with V3.0)? That would be great.

**Comment by karussell** [comment]
We only deploy our artifacts to maven central and would also not accept PRs with other branches. 

I.e. for now we either update graphhopper (incrementally to the latest JTS version) or only accept changes here where JTS is unchanged.

**Comment by tboegner** [comment]
Another version of the library is available as an "unsupported" geotools module: gt-geojsondatastore.

**Comment by karussell** [comment]
We have now upgraded JTS and a new version 2.14 of this library here will show up soon on maven central.
It is now more likely that we upgrade it more often (still no guarantee ;))

**Pull request closed without merging**
